name: Deploy Webapp

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2 # Set up Docker Buildx for multi-platform builds (optional)

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'  # Skip for pull requests
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t webapp/fastapi-test .

      - name: Run tests
        run: docker run -e CI=true webapp/fastapi-test pytest

      - name: Clean up
        if: always()  # Ensure this step runs even if tests fail
        run: |
          docker stop fastapi-container
          docker rm fastapi-container