name: Deploy Webapp

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'  # Skip for pull requests
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t webapp/fastapi-app .

      - name: Run Test
        run: docker run -e CI=true webapp/fastapi-app pytest

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: webapp
          environment_name: Webapp-env
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-509399619983
          region: ap-southeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
